### ISSUE TITLE
Running this on Linux

### ISSUE THREAD

**Issue by jochemstoel** [Lucas8x/luscious-downloader#16]
When I try to _pip install_ or _git clone then run setup_ On Ubuntu, I receive all sorts of error messages. 
How much effort would it take to get this working on Linux too?

I don't need it to work from source, a binary executable file _lsd_ that I can _chmod a+x_ works for me too.

**Comment by Lucas8x** [comment]
The cli should work normally on linux, can you send what error messages you're receiving?

**Comment by jochemstoel** [comment]
Thank you for your response. These are my steps.

## Environment
I use Conda on _Ubuntu 16.04.7 LTS (GNU/Linux 2.6.32-042stab145.3 x86_64)_.

```bash
conda create luscious
conda activate luscious
pip install luscious-downloader
```
### Output
```
Collecting luscious-downloader
  Downloading https://files.pythonhosted.org/packages/f9/63/0583a0a83f656579696fc8ede372cb537b065d128838acdc067f96fdf528/luscious-downloader-4.6.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-cTLU19/luscious-downloader/setup.py", line 5, in <module>
        with open('requirements.txt') as r:
    IOError: [Errno 2] No such file or directory: 'requirements.txt'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-cTLU19/luscious-downloader/
``` 

Apparenty it can not find requirements.txt so then I tried git clone and install.

```bash
git clone https://github.com/Lucas8x/luscious-downloader.git
cd luscious-downloader
python setup.py install
```
### Output
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site.py", line 563, in <module>
    main()
  File "/usr/lib/python2.7/site.py", line 545, in main
    known_paths = addusersitepackages(known_paths)
  File "/usr/lib/python2.7/site.py", line 272, in addusersitepackages
    user_site = getusersitepackages()
  File "/usr/lib/python2.7/site.py", line 247, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/usr/lib/python2.7/site.py", line 237, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/usr/lib/python2.7/sysconfig.py", line 582, in get_config_var
    return get_config_vars().get(name)
  File "/usr/lib/python2.7/sysconfig.py", line 528, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/usr/lib/python2.7/sysconfig.py", line 412, in _init_posix
    from _sysconfigdata import build_time_vars
  File "/usr/lib/python2.7/_sysconfigdata.py", line 6, in <module>
    from _sysconfigdata_nd import *
ImportError: No module named _sysconfigdata_nd
```
## Python2.7 vs Python3
Then I realized I am using Python 2.7, maybe I need Python3!

## Trying with Python3 
```bash
conda create --name luscious python=3
conda activate luscious
pip install luscious-downloader
```
### Output
```
Collecting luscious-downloader
  Using cached https://files.pythonhosted.org/packages/f9/63/0583a0a83f656579696fc8ede372cb537b065d128838acdc067f96fdf528/luscious-downloader-4.6.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-PHxrHn/luscious-downloader/setup.py", line 5, in <module>
        with open('requirements.txt') as r:
    IOError: [Errno 2] No such file or directory: 'requirements.txt'
```
Okay, the requirements.txt error again.

## Trying setup.py in Python3 environment
```bash
git clone https://github.com/Lucas8x/luscious-downloader.git
cd luscious-downloader
python setup.py install
```
### Output
```
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
ImportError: No module named site
```

Here it can not find module named 'site'. I am not very experienced with all this. Maybe it has something to do with $PYTHONHOME not having a value but if that is the problem I have no idea what so set it to.

Hope this helps.

**Comment by Drack112** [comment]
# Using Python 3.9.2

* OS: Solus Linux
* Python: 3.9.2
* Shell: Bash
* Pip: 3.9.2

## My solution:

Install Python 3.9.2 by compiling it from source, change your rc shell (barshrc, zshrc ...) and set up an alias for your new Python version. After that try to install the program again or using the pip. **(In my case, pip work's better)**

**NOTE: Uninstall the luscious downloader if you have setup it before.**

### Setting the standard version of python in your shell:

https://linuxconfig.org/how-to-change-from-default-to-alternative-python-version-on-debian-linux

### Compiling using source code:

https://realpython.com/installing-python/#how-to-build-python-from-source-code
