### ISSUE TITLE
User Download Options not working

### ISSUE THREAD

**Issue by Th3Commodore** [Lucas8x/luscious-downloader#24]
Every time I try to use option 3 it gives me this error:
```
Traceback (most recent call last):
    File "P:\Misc\Luscious Downloader\2 Electric Boogaloo\luscious_dl\menu.py", line 102, in <module>                         
        menu()                                                                                                               
    File "P:\Misc\Luscious Downloader\2 Electric Boogaloo\luscious_dl\menu.py", line 62, in menu
        start(args)
    File "P:\Misc\Luscious Downloader\2 Electric Boogaloo\luscious_dl\start.py", line 127, in start
        args.only_favorites, args.gen_pdf, args.rm_origin_dir, args.group_by_user)
AttributeError: 'Namespace' object has no attribute 'group_by_user'
Press any key to continue . . .                            
```
Edit:
When examining the code, it seems that "args.group_by_user" is not necessary in line 127 of start.py.
[https://drive.google.com/file/d/11yWauBSuxlu1pyRehfsNd4bnIzkWUiBm/view?usp=sharing](url) Here's the updated one. I just removed the args.group_by_user from line 127 and it started working.

**Comment by Lucas8x** [comment]
Fixed
Thank you ^^
