### ISSUE TITLE
Not working, error object is not subscriptable (opensuse leap 15.4)

### ISSUE THREAD

**Issue by MetaStazz** [Lucas8x/luscious-downloader#31]
After I installed everything using `sudo python3 setup.py install`
Everything is fine, I mean no error...

But when I try to download an album, I get this error :

```shell
Traceback (most recent call last):
  File "/usr/bin/lsd", line 11, in <module>
    load_entry_point('luscious-downloader==4.11.0', 'console_scripts', 'lsd')()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.6/site-packages/luscious_downloader-4.11.0-py3.6.egg/luscious_dl/start.py", line 5, in <module>
    from luscious_dl.album import Album, search_albums, print_search
  File "/usr/lib/python3.6/site-packages/luscious_downloader-4.11.0-py3.6.egg/luscious_dl/album.py", line 8, in <module>
    from luscious_dl.downloader import Downloader
  File "/usr/lib/python3.6/site-packages/luscious_downloader-4.11.0-py3.6.egg/luscious_dl/downloader.py", line 9, in <module>
    from luscious_dl.utils import create_folder
  File "/usr/lib/python3.6/site-packages/luscious_downloader-4.11.0-py3.6.egg/luscious_dl/utils.py", line 26, in <module>
    def inputs_string_to_list(inputs_string: str) -> list[str]:
TypeError: 'type' object is not subscriptable
```

**It worked fine on leap 15.3 !!**

**Comment by MetaStazz** [comment]
I resolved it by installing with python 3.10 !!
