### ISSUE TITLE
Banned album not put in log or skipped

### ISSUE THREAD

**Issue by PiPerson7472** [Lucas8x/luscious-downloader#8]
https://members.luscious.net/albums/katyuska-moonfox-blair-soul_368792/
[16:04:44] [MSG] Checking List.
[16:04:45] [MSG] Total of Links: 14788.
[16:04:45] [MSG] Resolving album id...
[16:04:45] [MSG] Fetching album information...
[16:04:45] [WARNING] Failed to print album information.
'title'
[16:04:45] [MSG] Fetching album pictures...
[16:04:45] [INFO] Total of 0 links found.
Traceback (most recent call last):
  File "luscious_dl\main.py", line 46, in <module>
    main()
  File "luscious_dl\main.py", line 33, in main
    start(url.rstrip('\n'))
  File "F:\luscious-downloader-master\luscious_dl\downloader.py", line 117, in start
    album_name = re.sub('[^\w\-_\. ]', '_', album_info['title'])
KeyError: 'title'
Press any key to continue . . .

The album was banned from the site but was not put in the log or skipped. I had to stop the program and manually remove the url to download again.

**Comment by Lucas8x** [comment]
Now they will ^^
